$(document).ready(function() {
    var json = [
        {"word": "apple"},
        {"word": "solar system"},
        {"word": "ball"},
        {"word": "cat"},
        {"word": "time"},
        {"word": "person"},
        {"word": "year"},
        {"word": "way"},
        {"word": "day"},
        {"word": "thing"},
        {"word": "man"},
        {"word": "world"},
        {"word": "life"},
        {"word": "hand"},
        {"word": "part"},
        {"word": "child"},
        {"word": "eye"},
        {"word": "woman"},
        {"word": "place"},
        {"word": "work"},
        {"word": "week"},
        {"word": "case"},
        {"word": "point"},
        {"word": "government"},
        {"word": "company"},
        {"word": "number"},
        {"word": "group"},
        {"word": "problem"},
        {"word": "fact"},
        {"word": "Verbs"},
        {"word": "be"},
        {"word": "have"},
        {"word": "do"},
        {"word": "say"},
        {"word": "get"},
        {"word": "make"},
        {"word": "go"},
        {"word": "know"},
        {"word": "take"},
        {"word": "see"},
        {"word": "come"},
        {"word": "think"},
        {"word": "look"},
        {"word": "want"},
        {"word": "give"},
        {"word": "use"},
        {"word": "find"},
        {"word": "tell"},
        {"word": "ask"},
        {"word": "work"},
        {"word": "seem"},
        {"word": "feel"},
        {"word": "try"},
        {"word": "leave"},
        {"word": "call"},
        {"word": "Adjectives"},
        {"word": "good"},
        {"word": "new"},
        {"word": "first"},
        {"word": "last"},
        {"word": "long"},
        {"word": "great"},
        {"word": "little"},
        {"word": "own"},
        {"word": "other"},
        {"word": "old"},
        {"word": "right"},
        {"word": "big"},
        {"word": "high"},
        {"word": "different"},
        {"word": "small"},
        {"word": "large"},
        {"word": "next"},
        {"word": "early"},
        {"word": "young"},
        {"word": "important"},
        {"word": "few"},
        {"word": "public"},
        {"word": "bad"},
        {"word": "same"},
        {"word": "able"},
        {"word": "Prepositions"},
        {"word": "to"},
        {"word": "of"},
        {"word": "in"},
        {"word": "for"},
        {"word": "on"},
        {"word": "with"},
        {"word": "at"},
        {"word": "by"},
        {"word": "from"},
        {"word": "up"},
        {"word": "about"},
        {"word": "into"},
        {"word": "over"},
        {"word": "after"},
        {"word": "beneath"},
        {"word": "under"},
        {"word": "above"},
        {"word": "Others"},
        {"word": "the"},
        {"word": "and"},
        {"word": "a"},
        {"word": "that"},
        {"word": "I"},
        {"word": "it"},
        {"word": "not"},
        {"word": "he"},
        {"word": "as"},
        {"word": "you"},
        {"word": "this"},
        {"word": "but"},
        {"word": "his"},
        {"word": "they"},
        {"word": "her"},
        {"word": "she"},
        {"word": "or"},
        {"word": "an"},
        {"word": "will"},
        {"word": "my"},
        {"word": "one"},
        {"word": "all"},
        {"word": "would"},
        {"word": "there"}
    ]

    var len = json.length;
    var searchText = "";
    $('.searchBar').on('keyup', function(event) {
        searchText = $('.searchBar').val();
        console.log('Search text: ' + searchText);

        $('.results').empty();
        $('.results').removeClass('active');
        console.log('emptied results');

        if (searchText != "") {
            $('.results').addClass('active');
            for (var i = 0; i < len; i++) {
                if(json[i].word.indexOf(searchText) >= 0) {
                    $('.results').append('<li>' + json[i].word + '</li>');
                }
            }
        }
    });
});